### ISSUE TITLE
issue with ya-errata-import.pl

### ISSUE THREAD

**Issue by ssenaria** [liedekef/spacewalk_scripts#22]
Not sure what changed but all of a sudden I'm getting the following error. I wonder if the CentOS digest changed. The only thing I've changed is the channel name.

    ./ya-errata-import.pl --erratadir=$ERRATADIR --server $SPACEWALK --channel centos-x86_64-updates-6 --os-version 6 --publish --quiet

    Use of uninitialized value $1 in concatenation (.) or string at ./ya-errata-import.pl line 1091. 
    Use of uninitialized value $2 in sprintf at ./ya-errata-import.pl line 1091.

**Comment by liedekef** [comment]
It should continue just fine, but the real reason is again a malformed Subject line for CentOS 7 in their errata announcements. I'll take it into account.
