### ISSUE TITLE
Centos erratas do not import properly

### ISSUE THREAD

**Issue by ssenaria** [liedekef/spacewalk_scripts#23]
I took a look at `centos-clone-errata.sh` and noticed the URL pointing to `http://lists.centos.org/pipermail/centos`. When I run the script, I get no erratas but after poking around the mailing list, i noticed the URL doesn't contain any errata information. I modified the URL to `http://lists.centos.org/pipermail/centos-announce` and it seems to have fixed my issue.

Is the URL correct?

**Comment by liedekef** [comment]
The script adds the year/mon + 'date.html" to it. E.g.: 
http://lists.centos.org/pipermail/centos/2015-April/date.html
and that still works fine.
