### ISSUE TITLE
Spacewalk username has to be "admin"

### ISSUE THREAD

**Issue by vikas027** [liedekef/spacewalk_scripts#25]
Just a note if someone bumps into this post. You will keep getting below error, unless a user "admin" is created with proper access (role of Channel Administrator).

```bash
INFO: Setting the OS variant to CentOS, if this is wrong please add the --redhat option
INFO: Server spacewalk.test.com is running API version 16
INFO: Your API version is supported
ERROR: Authentication on spacewalk.test.com FAILED!
```

**Comment by liedekef** [comment]
The moment you log in, this is not tested. Any user that is capable of logging in via the web interface, should be able to log in via the API too. The test for admin rights is done afterwards and you get an appropriate error if you don't have the needed rights. Of course, anybody trying to add something to a channel (errata) without being at least channel admin will get an error ...

**Comment by vikas027** [comment]
No, earlier I had create a user "vikas027" which is a Satellite administrator. The api failed for this user. It only worked when I created another user "admin". 

FYI, I am using v2.3 of Spacewalk

**Comment by liedekef** [comment]
The user doesn't need to be satellite admin, but org admin. Maybe that was the problem?
