### ISSUE TITLE
ERROR: Couldn't log in to redhat: 404 Not Found

### ISSUE THREAD

**Issue by belgiumrom** [liedekef/spacewalk_scripts#30]
Just some weird issue, using spacewalk, when executing I get this. I have access to rhn.com, I have an account, I added the RH6 (i386 and x86_64) and sync using mrepo. But getting errata is no go. Any idea?

[root@server_name scripts]# ./ya-errata-import.pl --server 127.0.0.1 --channel rhel6-x86_64 --os-version 6 --publish --redhat --redhat-channel=rhel-x86_64-server-6 --startfromprevious month
INFO: Architecture is not specified, will try to determine it based on the channel properties of 'rhel6-x86_64'
INFO: Setting the OS variant to Redhat, if this is wrong please remove the --redhat option
INFO: Server 127.0.0.1 is running API version 17
INFO: Your API version is supported
INFO: Authentication on 127.0.0.1 successful
Please enter RHN username: xxxx
Please enter RHN password:
ERROR: Couldn't log in to redhat: 404 Not Found

**Comment by liedekef** [comment]
a 404 is never generated by this script, so you'll need to look elsewhere for this ...
