### ISSUE TITLE
API support version

### ISSUE THREAD

**Issue by nahga** [liedekef/spacewalk_scripts#31]
I have an issue with spacewalk v2.3 The returned API version is 16, and according to "my @supportedapi" API version 16 is supported, but I still receive the following error.

sh redhat-clone-errata.sh
INFO: Architecture is not specified, will try to determine it based on the channel properties of 'rhel-6-x86-64'
INFO: Setting the OS variant to Redhat, if this is wrong please remove the --redhat option
INFO: Server spacewalk is running API version 16
ERROR: Your API version (16) is not supported. Try upgrading this script.

**Comment by liedekef** [comment]
Which version of the script are you running?

**Comment by nahga** [comment]
I am running the version I checked out yesterday, 2016-02-02.

**Comment by liedekef** [comment]
Can it be that your redhat-clone-errata.sh uses another version of the perl script?

**Comment by nahga** [comment]
The version I am using is coming directly from what was checked out from your repo. I'll try to delete it all and re-git it again.

Thanks for replying so quickly. I appreciate it.

**Comment by nahga** [comment]
After re-download the repo, I made only changes to ya-errata-import.cfg(to change the credentials) and to redhat-clone-errata.sh(to change the spacewalk server address), I am still getting the same error:

sh redhat-clone-errata.sh
ERROR: Your API version (16) is not supported. Try upgrading this script.

**Comment by liedekef** [comment]
redhat-clone-errata.sh (which is an example only btw, and needs to be adapted to your needs) uses /sbin/ya-errata-import.pl , did you put the perl script there? You need to check that the shell script uses your latest downloaded perl script too ...

**Comment by nahga** [comment]
That was it entirely. There was an older version in /sbin and all the while I kept troubleshooting the one in the downloaded dir. Thanks again.
