### ISSUE TITLE
Support Fedora (non-EPEL) Errata & fix type-subset bug when advisory doesn't contain SA|BA|EA keyword

### ISSUE THREAD

**Issue by fermulator** [liedekef/spacewalk_scripts#37]
While attempting to get Errata imported into Spacewalk for Fedora repositories, I stumbled over:
 1) one basic tweak/fix to include the FEDORA errata naming convention
 2) an unlikely defect in handling type!=all errata types

I've forked this repo with the fix, and will initiate a pull request for discussion/approval.

**Comment by fermulator** [comment]
https://github.com/liedekef/spacewalk_scripts/pull/38

**Comment by liedekef** [comment]
Merged, I'll make a small change to it, but nothing big.
