### ISSUE TITLE
ya-errata-import.pl no longer supported spacewalk 2..7

### ISSUE THREAD

**Issue by xxdrew21xx** [liedekef/spacewalk_scripts#42]
Hi ,
I'm been using the script on spacewalk v2.6 and its doing great but after i upgraded to spacewalk v2.7 its no longer working and receiving error message that api not supported. Is it possible to have an updated script that support spacewalk v2.7 Thanks

./ya-errata-import.pl --server spacewalk.internal --erratadir=/tmp/centos-errata --channel=centos5x-base-x86_64 --os-version 5  --rhsa-oval com.redhat.rhsa-all.xml  --get-from-rhn --publish
INFO: Architecture is not specified, will try to determine it based on the channel properties of 'centos5x-base-x86_64'
INFO: Setting the OS variant to CentOS, if this is wrong please add the --redhat option
INFO: Server spacewalk.internal is running API version 20
ERROR: Your API version (20) is not supported. Try upgrading this script.

**Comment by liedekef** [comment]
Solved in release from today.

**Comment by xxdrew21xx** [comment]
Thanks for the quick response. 
Cheers!
