### ISSUE TITLE
CentOS updates are frequently missing from the digests... suggested workaround

### ISSUE THREAD

**Issue by sandwormusmc** [liedekef/spacewalk_scripts#44]
We've been using the script with quite a bit of hacking/additions that I've done, and I've noticed that quite a few advisories are missed in the digests for some reason.  To work around that, I've added the below to the CentOS shell script we are using

>    # Also scrape the actual CentOS-announce mailing list since the digests are not completely reliable
>    listurl=https://lists.centos.org/pipermail/centos-announce
>    { for d in $yearmon; do
> 	  wget --no-cache -q -O- $listurl/$d/date.html \
> 		| sed -n 's|.*"\([^"]*\)".*\[CentOS-announce\].*CE.A.*|'"$d/\\1|p"
>      done
>    } | tail -n $NBR_DIGESTS | xargs -n1 -I{} wget -q $listurl/{}`

Specific examples of errata missed by using the stock shell script are below:

INFO: Creating errata CEBA-2017:0889:C6-64 for CEBA-2017:0889 (CentOS 6 samba BugFix Update ) (All 18 packages present in the corresponding channel)
INFO: Processing CEBA-2017:0891 (CentOS 6 binutils BugFix Update )
INFO: Creating errata CEBA-2017:0891:C6-64 for CEBA-2017:0891 (CentOS 6 binutils BugFix Update ) (All 3 packages present in the corresponding channel)
INFO: Processing CEBA-2017:0894 (CentOS 6 glibc BugFix Update )
INFO: Creating errata CEBA-2017:0894:C6-64 for CEBA-2017:0894 (CentOS 6 glibc BugFix Update ) (All 10 packages present in the corresponding channel)
INFO: Creating errata CEEA-2017:0890:C6-64 for CEEA-2017:0890 (CentOS 6 nss-util Enhancement Update ) (All 4 packages present in the corresponding channel)
INFO: Creating errata CESA-2017:0892:C6-64 for CESA-2017:0892 (Important CentOS 6 kernel Security Update ) (All 11 packages present in the corresponding channel)
...

I'm sure there are more, but this was a pain point in our CentOS 7 channels as it caused multiple dependency issues (perhaps more related to a spacewalk-clone-by-date issue or the way the channels were created).

Anyway, hope it helps someone if it's incorporated into the project.  Perhaps I should have submitted a pull request...

**Comment by liedekef** [comment]
Soory, I let this one slop by too long. Would it be possible to generate a pull request?

**Comment by sandwormusmc** [comment]
I also let it slop by quite a while... :)

I'm looking at it again and have added CentOS-CR-announce as well, since some of those were missing.

I also have another issue in the parse_message area relating the i386/i686, which I'll create a separate issue for.

**Comment by sandwormusmc** [comment]
https://github.com/liedekef/spacewalk_scripts/pull/46

**Comment by sandwormusmc** [comment]
Also needed to modify the ya-errata-import.pl to update the regex used there, otherwise it wasn't parsing the errata from CentOS-CR-announce, another pull request incoming as soon as I test
